name: Trigger Backend Action to Deploy

on: [push]

##on:
##  push:
##    branches: 
##      - deployment

jobs:
  dispatch:
    environment: dev
    runs-on: ubuntu-latest
    steps:
    - name: trigger-workflow-in-different-repo
      uses: actions/github-script@v6
      with:
        github-token: ${{ secrets.ACCESS_TOKEN }}
        script: |
          try {
            const result = await github.rest.actions.createWorkflowDispatch({
              owner: 'tskuit',
              repo: 'blax-a',
              workflow_id: 'github-dispatch.yaml',
              ref: 'main'
#              inputs: {
#                tags: ${{ steps.get-tags.outputs.tags }}
#              },
            })
            console.log(result);
          } catch(error) {
            console.error(error);
            core.setFailed(error);
          }



          const result = await github.rest.actions.createWorkflowDispatch({
            owner: 'patternfly',
            repo: 'patternfly-elements',
            workflow_id: 'bundle.yml',
            ref: 'main',
            inputs: {
              tags: ${{ steps.get-tags.outputs.tags }}
            },
          })
          console.log(result);
        } catch(error) {
          console.error(error);
          core.setFailed(error);
        }
